# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial32"
  config.vm.provider :virtualbox do |vb|
   vb.customize [ 'modifyvm', :id, '--name', 'servidorweb', "--memory", "512","--cpus","1" ]
  end
  config.vm.network "forwarded_port", guest: 80, host: 8008
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", path: "script.sh"
  config.vm.synced_folder "html", "/var/www/html"
end
